* How-to release a new version of SF

This document how to create a release of the software factory project (SF).

** Terminology
*** SemVer

SF is using SemVer, or Breaking.Feature.Fix, for example:

2.5.0: add diskimage builder support
2.5.1: add minor fix that can be applied without running upgrade process
2.6.0: add zuul-launcher support in paralell of jenkins, upgrade from 2.5.x is trivial
3.0.0: drop jenkins support, upgrade from 2.y is non trivial

A feature release, or feature version only include the first two numbers.

*** Koji targets

Koji target defines a build environment: an architecture and base repository
SF is using a koji target per feature, e.g. 2.6 or 3.0

*** Koji tags

Koji tags defines a collection of package build. By default a target needs two tags:
  - *targetname-build*: includes the baserepos and extrarepos packages
  - *targetname*: only includes the SF packages

Then we use two extra tag for stable branch:

  - *targetname-candidate*: include the set of package we want to release. New ci build doesn't end up there.
  - *targetname-release*: a copy of candidate once it's fully tested

** Procedure to branch from master
*** Prepare the distro info

GOAL: define the koji target and the list of packages (like that, new projects don't get included in stable)
RESULT: a yaml file

In the sfinfo repository, create a new description for the release:

$ cp sf-master.yaml sf-2.6.yaml

Change the
 - *koji-target*: the name of the new target
 - *koji-url*: the url to be used in CI script
 - *branch*: the git branch that will use the target

Send the review and approve the change before the step "Update the sf-release package"

*** Create the koji target

GOAL: create the koji resources
RESULT: the koji target and 4 tags

As the koji admin user, run the script (included in sfinfo):

$ ./zuul_koji_set_target.py --distro-info sf-2.6.yaml

Expected results: newRepo (sf-2.6-el7-build) completed successfully

**** TODO automate bellow dist info setting
In order to have the correct Release dist (el7), a package needs to be added to the build tag:

$ koji add-pkg sf-2.6-el7-build buildsys-macros-el7 --owner sfci
$ koji tag-build sf-2.6-el7-build buildsys-macros-el7-1.0-0.el7.centos

*** Create the project branches

GOAL: branch all the project to prevent new/unstable change to be included
RESULT: a config project review with branch creation

As the root user on the sf instance, run the script (also included in sfinfo):

$ ./zuul_set_distro_branch.py --distro-info sf-2.6.yaml --push-branch

**** TODO Add excepted results: add expected CLI result, e.g. the last line

*** Populate the target

GOAL: import all the build from master that match the content of the branch
RESULT: a target populated

As the koji admin user, run the script (included in sfinfo):

$ ./zuul_koji_populate_target.py --distro-info sf-2.6.yaml --update

It may occurs the command fails when a repository does not contain a
valid .spec file. In that case just comment or remove the related repo
in the sf-2.6.yaml file and run again the command.

Expected results: INFO  [zuulkoji.ZuulKojiPopulateTarget] SUCCESS: sf-2.6-el7 is populated

*** Merge the new distro info

GOAL: Merge the new distro info file for the release (sf-2.6.yaml)
RESULT: A working sfinfo project for the new branch that will be used for further steps

$ cd sfinfo
$ git add sf-2.6.yaml
$ git commit -m "Add stable info file"
$ git push # or git review and +2/+A

** Prepare the release
*** Update the sf-release package

GOAL: change the release repository information
RESULT: a usable sf-release package

Change sf-release.repo to point at: kojifiles/repos/sf-2.6-el7-release
and change the repository name to [sfrelease-2.6]
Change the sf-release.spec version to 2.6, bump the release number
and change the /etc/sf-release content (echo 2.6 > /etc/sf-release)

software-factory/sf-release need to be cloned
git checkout 2.6
Make the changes
then git review 2.6

*** Tag all the internal projects

GOAL: get real version number instead of -dev git describe
RESULT: all internal project (sf-docs, sf-release, cauth, managesf, ...) are tagged

Tag projects with relevant version number, for example managesf:

$ git checkout origin/2.6
$ git tag -a -m "0.9.3" 0.9.3 HEAD^
$ git push --tag gerrit

Note: do not tag the .gitreview change, use HEAD^ instead so that the tag applies
      to master branch too. If master and stable branch content are identical
      (minus the .gitreview update), then master tip can be tag instead.

Wait for zuul tag pipeline to finish.

*** Import newly tagged build to the stable target

GOAL: first tag on the branch shall be shared with master and the branch, thus it has been published on master target
RESULT: import newly tagged build from master target to stable target

As the koji admin user, run the script:

$ ./zuul_koji_populate_target.py --update --internal --distro-info sf-2.6.yaml

Expected results: INFO  [zuulkoji.ZuulKojiPopulateTarget] SUCCESS: sf-2.6-el7 is populated

*** Populate the candidate target

GOAL: import all the build from the stable tag to the candidate tag
RESULT: a candidate tag populated

As the koji admin user, run the script:

$ ./zuul_koji_populate_target.py --distro-info sf-2.6.yaml --candidate
$ ./zuul_koji_mash.py --distro-info sf-2.6.yaml

To test, install the sf-release-2.6 package and change the repo url to:
http://46.231.133.231/kojifiles/repos/sf-2.6-el7-candidate

Good time to do preprod test

*** Create the release tag and repository

GOAL: freeze the candidate tag
RESULT: a release tag and repository

As the koji admin user, run:

$ koji clone-tag sf-2.6-el7-candidate sf-2.6-el7-release
$ ./zuul_koji_mash.py --distro-info sf-2.6.yaml --release


** Finalise the release

- Get the TEMP_URL_KEY from jenkins secrets
- Get the release signing key from SF_password_store

*** Create the final artifacts

$ git clone https://softwarefactory-project.io/r/software-factory/sf-elements
$ pushd sf-elements
$ SF_RELEASE=2.6 ./scripts/create_sf_image.sh
$ popd

$ git clone https://softwarefactory-project.io/r/software-factory/sf-heat-templates
$ pushd sf-heat-templates
$ ./render.py --arch ../sf-config/refarch/minimal.yaml --version 2.6
$ ./render.py --arch ../sf-config/refarch/allinone.yaml --version 2.6
$ ./render.py --arch ../sf-config/refarch/distributed.yaml --version 2.6
$ popd

$ mkdir release-2.6
$ pushd release-2.6
$ mv ../sf-elements/sf-2.6.qcow2 ../sf-heat-templates/*.hot .
$ popd

*** Sign the digest

$ pushd release-2.6
$ sha256sum * > sf-2.6.digest
$ gpg -u release@softwarefactory-project.io --clearsign sf-2.6.digest
$ mv sf-2.6.digest.asc sf-2.6.digest
$ popd


*** Upload artifacts

$ pushd release-2.6
$ TEMP_URL_KEY="***"
$ SWIFT_BASE_URL="http://46.231.132.68:8080"
$ SWIFT_ACCOUNT="b50e80d3969f441a8b7b1fe831003e0a"
$ SWIFT_IMAGE_CONTAINER="sf-images"
$ for OBJECT in *; do
    OBJECT=`echo $OBJECT | sed 's|^\./||'`
    SWIFT_PATH="/v1/AUTH_${SWIFT_ACCOUNT}/talks/${OBJECT}"
    TEMPURL=`swift tempurl PUT 900 ${SWIFT_PATH} ${TEMP_URL_KEY}`
    curl -f -i -X PUT --upload-file "$OBJECT" "${SWIFT_BASE_URL}${TEMPURL}" && echo -n '.' || { echo 'Fail !'; exit 1; }
  done
$ popd

*** Deploy for test day

$ git clone https://softwarefactory-project.io/r/software-factory/sf-ci
$ pushd sf-ci
$ ansible-playbook -M modules/ -e sf_version=2.6 -v playbooks/deploy-heat.yml
$ popd

*** Generate changelog

**** TODO: need a script to compare package from previous version

In the meantime, look at git logs and generate a changelog manually...

For example, for sf-config, run:

$ report  --no-show-source --version 2.6.0

*** Publish the sf-release package on softwarefactory-project.io/repos:

From the sf instance:

$ curl -o /var/www/repos/sf-release-2.6.rpm http://46.231.133.231/kojifiles/repos/sf-2.6-el7-release/Mash/sf-release-2.6.0-1.el7.noarch.rpm

*** Send announce

**** TODO: have a template ready to include
 - changelog
 - packages diff
 - digest
 ...
In the meantime, look at previous announce and reproduce

*** Update sf-upgrade test

$ git clone https://softwarefactory-project.io/r/config
$ pushd config
$ vim jobs/softwarefactory.yaml # change version: of 'sf-ci-{type}-{arch}' upgrade type
$ git commit -m "sf: update upgrade version of sf-ci"
$ git review
$ popd
