gantt
    title Logreduce web interface file size
    todayMarker off
    dateFormat  X
    axisFormat %sKB

    section Before
    HTML Report   : 0, 881
    section After
    Binary Report : 0, 148
    WASM Viewer   : 148, 673
